- name: Magento Setup
  hosts: localhost
  tasks:
      - name: Restarting sshd
        shell: "sed -i 's/#Match User anoncvs/ForceCommand echo Please wait until the installation is completed..../g' /etc/ssh/sshd_config && systemctl restart sshd"

      - name: Updating Packages
        ansible.builtin.apt:
          update_cache: yes
         
      - debug:
         msg: "Installing Apache"

      - name: Installing apache
        apt:
          name: [ 'apache2' , 'python3-certbot-apache', 'zip' ]
          state: latest

      - name: Removing site files
        file:
          path: "{{ item }}"
          state: absent
        with_items: 
          - /etc/apache2/sites-available/000-default.conf
          - /etc/apache2/sites-enabled/000-default.conf
          - /var/www/html/index.html

      - name: Copy files
        copy:
          src: "{{ item.confsrc }}"
          dest: "{{ item.confdest }}"
        with_items: 
          - { confsrc: '/usr/local/src/magento2-20-04/etc/apache2/sites-available/magento2.conf', confdest: '/etc/apache2/sites-available/'}
          - { confsrc: '/usr/local/src/magento2-20-04/var/www/html/index.html', confdest: '/var/www/html/'}

      - name: Renaming the file
        shell: mv /etc/apache2/sites-available/magento2.conf /etc/apache2/sites-available/000-default.conf

      - name: Creating a symlink
        ansible.builtin.file:
          src: "/etc/apache2/sites-available/000-default.conf"
          dest: "/etc/apache2/sites-enabled/000-default.conf"
          state: link

      - name: Starting service apache2
        service:
          name: apache2
          state: started 

      - name: Getting the status of the service
        shell: systemctl status apache2 | grep 'since'
        register: status

      - debug:
          var: status.stdout 

      - name: Replacing the port
        replace:
          path: /etc/apache2/ports.conf
          regexp: '80'
          replace: '127.0.0.1:8080'

      - name: Enable mod-rewrite
        shell: a2enmod rewrite

      - name: Restart apache
        service:
           name: apache2
           state: restarted 

      - debug:
         msg: "Installing Mysql"

      - name: Installing mysql
        apt:
          name: mysql-server
          state: latest

      - name: Starting service mysql
        service:
          name: mysql
          state: started 

      - name: Getting the status of the service
        shell: systemctl status mysql | grep 'since'
        register: status

      - debug:
          var: status.stdout 

      - name: Generating root password
        shell: openssl rand -hex 24
        register: rootpassword

      - debug:
         var: rootpassword.stdout

      - name: Storing mysql password
        copy:
          dest: "/root/.mysql_root_password"
          content: |
            root_mysql_pass = "{{ rootpassword.stdout }}"
            
      - name: Remove anonymous users
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - DELETE FROM mysql.user WHERE User=''
        changed_when: False

      - name: Disallow root login remotely
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
        changed_when: False

      - name: Remove test database and access to it
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - DROP DATABASE IF EXISTS test
          - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
        changed_when: False

      - name: Reload privilege tables
        command: 'mysql -ne "{{ item }}"'
        with_items:
          - FLUSH PRIVILEGES
        changed_when: False

      - name: Alter Password
        shell: "{{ item }}"
        with_items:
          - mysql -n --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ rootpassword.stdout }}';"

      - debug:
          msg: "Mysql root password is stored under /root/.mysql_root_password"

      # - name: Change login type
      #   shell: 'mysql -u root -p{{ rootpassword.stdout }} -n --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;" > /dev/null 2>&1'

      - name: Generating magento password
        shell: openssl rand -hex 24
        register: magentopassword

      - debug:
         var: magentopassword.stdout

      - name: Storing magento password
        copy:
          dest: "/root/.magento_database_details"
          content: |
            magento_database_name = magento_db          
            magento_database_user = magento_user
            magento_user_password = "{{ magentopassword.stdout }}"

      - name: Creating Magento2 DB configurations
        shell: "{{ item }}"
        with_items:
          - mysql -e 'create database magento_db' -u root -p{{ rootpassword.stdout }}
          - mysql -e "CREATE USER 'magento_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ magentopassword.stdout }}';" -u root -p{{ rootpassword.stdout }}
          - mysql -e "GRANT ALL PRIVILEGES ON magento_db.* TO 'magento_user'@'localhost';" -u root -p{{ rootpassword.stdout }}

      - debug:
         msg: "Installing PHP"

      - name: Installation install software-properties-common
        apt: name=software-properties-common
      
      - name: "Repo PHP 8.1"
        apt_repository:
          repo="ppa:ondrej/php"
    
      - name: Installation PHP
        apt: 
          name: php8.1
          state: present

      - shell: php -v
        register: phpversion

      - debug:
          var: phpversion.stdout_lines 

      - name: Installation PHP dependencies
        apt: 
          name: [ 'php8.1-xml' , 'php8.1-curl' , 'php8.1-zip' , 'php8.1-bcmath' , 'php8.1-soap' , 'php8.1-mysql' , 'php8.1-mbstring' , 'php8.1-intl' , 'php8.1-imagick' , 'php8.1-gd' , 'php8.1-bz2']
          state: present

      - name: Installing Composer
        shell: chmod +x /usr/local/src/magento2-20-04/composer.sh && /usr/local/src/magento2-20-04/composer.sh

      - name: Copy Composer file
        copy:
          src: /usr/local/src/magento2-20-04/composer.phar
          dest: /usr/local/bin/composer
          remote_src: yes

      - name: Setting permission for composer
        ansible.builtin.file:
          path: /usr/local/bin/composer
          mode: '0755'

      - name: Adding key elasticsearch
        apt_key:
          url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          state: present

      - name: Adding repo elasticsearch
        ansible.builtin.apt_repository:
          repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
          state: present

      - name: Adding key varnish
        apt_key:
          url: https://packagecloud.io/varnishcache/varnish64/gpgkey
          state: present

      - name: Adding repo varnish
        ansible.builtin.apt_repository:
          repo: "deb https://packagecloud.io/varnishcache/varnish64/ubuntu/ xenial  main"
          state: present

      - name: Download varnish dependencies
        ansible.builtin.get_url:
          url: https://repo.percona.com/apt/pool/main/j/jemalloc/libjemalloc1_3.6.0-2.focal_amd64.deb
          dest: /usr/local/src/
      
      - name: Installing varnish dependencies 
        apt: 
          deb: /usr/local/src/libjemalloc1_3.6.0-2.focal_amd64.deb
          
      - name: Updating Packages
        ansible.builtin.apt:
          update_cache: yes
      
      - name: Installing Elasticsearch 
        apt: 
          name: elasticsearch
          state: present

      - name: Enable services and start
        ansible.builtin.systemd:
          name: elasticsearch
          state: started
          enabled: true

      - name: Installing varnish 
        apt: 
          name: varnish
          state: present

      - name: Enable services and start
        ansible.builtin.systemd:
          name: varnish
          state: started
          enabled: true

      - name: Generating secret key file for varnish 
        shell: uuidgen | sudo tee /etc/varnish/secret

      - name: Setting permission for the secret key file for varnish 
        ansible.builtin.file:
          path: /etc/varnish/secret
          mode: '0600'         

      - name: Replacing the service file
        replace:
          path: /lib/systemd/system/varnish.service
          regexp: 'ExecStart'
          replace: '#ExecStart'

      - name: Replacing the service file
        lineinfile:
          path: /lib/systemd/system/varnish.service
          insertafter: "#ExecStart"
          line: 'ExecStart=/usr/sbin/varnishd -j unix,user=vcache -a :80 -T localhost:6081 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s Cache=malloc,256m -s Transient=malloc,64m 
                -p listen_depth=16383 
                -p thread_pool_stack=512k 
                -p thread_pools=2 
                -p http_resp_hdr_len=65536 
                -p http_resp_size=98304 
                -p workspace_client=256k 
                -p workspace_backend=256k'

      - name: Reload Daemon
        ansible.builtin.systemd:
          daemon_reload: true

      - name: Restart varnish
        service:
           name: varnish
           state: restarted 

      - name: Installing redis server 
        apt:
          name: redis
          state: latest
          
      - name: Creating a directory auth.json
        ansible.builtin.file:
          path: /var/www/.config/composer
          state: directory 
          recurse: yes

      - name: Copying auth.json
        copy:
          src: /usr/local/src/magento2-20-04/var/www/.config/composer/auth.json 
          dest: /var/www/.config/composer/

      - name: Change ownership of a directory
        ansible.builtin.file:
          path: /var/www/
          owner: www-data
          group: www-data
          recurse: yes

      - name: Creating a directory for shell script
        ansible.builtin.file:
          path: /opt/cloudstack
          state: directory         
          
      - name: Copy files for shell script
        copy:
          src: "{{ item.confsrc }}"
          dest: "{{ item.confdest }}"
        with_items: 
          - { confsrc: '/usr/local/src/magento2-20-04/opt/cloudstack/magento2-cleanup.sh', confdest: '/opt/cloudstack/'}     
          - { confsrc: '/usr/local/src/magento2-20-04/opt/cloudstack/update_config.php', confdest: '/opt/cloudstack/'}     
          
      - name: Adding a line for shell script
        lineinfile:
          path: /root/.bashrc
          line: "chmod +x /opt/cloudstack/magento2-cleanup.sh && /opt/cloudstack/magento2-cleanup.sh"
          state: present
         
      - name: Restarting sshd
        shell: "sed -i 's/ForceCommand echo Please wait until the installation is completed..../#Match User anoncvs/g' /etc/ssh/sshd_config && systemctl restart sshd"
